fix: Fribbs JSON Parsing
The fribbs downloads were failing to parse the imdb_id formats in the new list
format.

    System.Text.Json.JsonException: The JSON value could not be converted to
    System.String. Path: 0.imdb_id | LineNumber: 8 | BytePositionInLine: 15.

This aligns the list mapper to the new fribbs format.